### ISSUE TITLE
Add saved draft functionality

### ISSUE THREAD

**Issue by irdan** [privly/privly-applications#135]
If a user types a message and then closes the window or accidentally clicks on a link on the message creation screen, the message is lost.  Users have come to expect applications to have the ability to recover from such simple mistakes.  

There are jquery plugins, [sisyphus.js](http://sisyphus-js.herokuapp.com/) and [garlic.js](http://garlicjs.org/), that are designed to provide this functionality.  I've not evaluated either very closely but they seem worth considering.

**Comment by bhavul** [comment]
Maybe, I'll start working on this. @smcgregor, @irdan tell me guys if you have any idea for its implementation, or I'll figure out something of my own?

**Comment by smcgregor** [comment]
@bhavul I think it would be better to add integration tests to the changes you are introducing on the History app. This will likely take you a day or two since it requires Selenium WebDriver, Ruby Unit Tests, Capybara, and (optionally) TravisCI+SauceLabs. You will definitely need help but it is very cool once you get it working.

**Comment by smcgregor** [comment]
The seamless posting method implicitly includes this functionality. Feel free to reopen or continue commenting if desired.
