### ISSUE TITLE
Obsolete chrome/firefox-extension-master?

### ISSUE THREAD

**Issue by SummerWish** [privly/privly-applications#206]
Since the difference between `chrome/firefox-extension-master` and `master` is only generated HTML, I think it is better to separate development and deployment explicitly, that is ignoring all changes made by `build.py` and then maintaining `master` branch only. (move build phase from development to deployment).

It is easy to build specific platform from source code when deploying:
```bash
git checkout .
python build.py --platform=chrome
# command to pack chrome extension here
```

Advantages:
- maintain source code only
- no more commits of generated HTML
- maintain one master branch, no more merge conflicts
- it's a *common pattern*, for example [jQuery](https://github.com/jquery/jquery/blob/master/.gitignore#L11) repo ignores all generated files in build phase

Disadvantages:
- cannot easily diff built files (if we can ensure the correctness of source code and building step, I think this isn't a big issue)

**Comment by smcgregor** [comment]
I think we are heading in this direction, but we won't make this transition until the next lull in development.

Disadvantages:

* We would need to run the build script on TravisCI for privly-chrome, privly-firefox, etc.
* It adds a step when people clone the project for the first time since `git clone --recursive` no longer gets rendered HTML.
* (maybe) To prevent people from failing to render the HTML, we would probably want to put a placeholder HTML page that tells them they still need to render the HTML.

**Comment by SummerWish** [comment]
Agree, maybe after GSoC LOL.

**Comment by smcgregor** [comment]
Summarizing my thoughts here. We need to change the way HTML is maintained in our code base because of the following considerations:

1. We don't update the HTML every time we update the templates or pages because it clutters the commit logs.
2. It is useful to view the diffs of HTML periodically to check for build issues without visually inspecting all HTML files.
3. It is annoying to have dirty HTML files locally that won't be committed by anyone but me (the person building HTML for the project)
4. The .travis.yml file does not build the HTML, which can break the build in some cases.
5. When new developers clone a server or extension they think it should work without building HTML.

Each of these considerations produces different recommendations, so it is important to find a proper balance.

1. For point (1), the solution is to either keep the file out of the git repo and add it to the .gitignore, or to explicitly ignore it locally by issuing `git update-index --assume-unchanged path/to/file`.
2. I should include the files in the source tree so I can easily track the differences in HTML versions through time. This rules out the first solution for point (1), so it is best to use the `--assume-unchanged` flag.
3. The `--assume-unchanged` flag solves this.
4. I'll add building HTML to the .travis.yml files.
5. I don't like forcing all new developers to run the build system before they can contribute. In practice the HTML does not introduce breaking changes very frequently that would require me to introduce the changes into the repo or for the developer to build the HTML themselves.

Conclusion:

People should issue: `find . -name \*.html -type f -exec git update-index --assume-unchanged '{}' \;` from the privly-applications repository to ignore all changes to HTML files. I will periodically undo this with
 `find . -name \*.html -type f -exec git update-index --no-assume-unchanged '{}' \;` so I can commit updated HTML to Git.

If this doesn't work for you, or if you have a better way, then please let me know.
